### ISSUE TITLE
Shouldn't `precision` default to `ms` since ms we use?

### ISSUE THREAD

**Issue by holyjak** [brandonhamilton/node-metrics-influxdb#20]
Unless I am mistaken, `metrics-influxdb` doesn't work correctly unless the option `precision: "ms"` is provided because it in fact uses milliseconds (via `var timestamp = new Date().getTime()`) but the `influxdb` module defaults to `'n'`.  So if you use `metrics-influxdb` to report your metrics, you will end up with timestamps in `1970-*`.

Therefore I think that we should default precision to `"ms"`. Agreed? Or perhaps I am missing something here?

**Comment by brandonhamilton** [comment]
You are correct. I think the default was set to `n` to match the default of influxdb, but the timestamps generated are actually in `ms` as you point out.
