### ISSUE TITLE
Add configuration field to support https.Agent setup

### ISSUE THREAD

**Issue by stathopou** [brandonhamilton/node-metrics-influxdb#27]
@brandonhamilton 
Thanks for creating this library, it has been very usefull, especially in data collection/aggregation. 

While working with the package, I needed to configure the https.Agent object to ignore SSL certificate. 

Should I create a pull request with the changes that have to be made to support this as well?

**Comment by Entea** [comment]
Hey @stathopou feel free to create a PR :)

**Comment by stathopou** [comment]
Thanks for the quick response @Entea !! I have created the PR, waiting for approval. Is there going to be a new release soon?
