### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Robbilie** [brandonhamilton/node-metrics-influxdb#5]
Thanks for this repo, should make my life much easier!
Currently trying to get it up and running, question is, does it work with 1.x too?
Getting a Bad Syntax Error using the http client with auth, also only when doing .report(true) because of https://github.com/brandonhamilton/node-metrics-influxdb/blob/master/lib/reporter.js#L162

Was also wondering why you didnt extend Reporter but chose to extend Report directly…

**Comment by Robbilie** [comment]
about the error, it was because the timer only had a single value and therefore pushed a NaN to influx which it didnt like
i got .start() to work passing it the true of report as the second arg…

**Comment by AllanCrain** [comment]
bug fix submitted for the need for report(true)

the issue with NaN I've seen comes from the metrics library underneath this one.
Its possible to fix it by putting an if statement in the reporter to only pass through certain fields to influx if they have more than one value but would be better to fix the underlying issue

**Comment by Robbilie** [comment]
Awesome :)
Although I switched back to graphite since I wasn't satisfied by grafanas/influx abilities to create the graphs I needed :/
